### ISSUE TITLE
Meta issue for Conda-Store user experience 

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1247]
Opening this issue to track all of the Conda-Store related user experience questions and issues. The goal is help users navigate the recent Conda-Store changes. Much of what is discussed below can be included in the docs eventually. 

Questions:
- [ ] When should new conda environments be created via the `nebari-config.yaml` and when should they be created from the `/conda-store` endpoint? And what difference does it make?
- [ ] What are the steps to delete a conda environment I no longer need?
- [ ] Add a feature that auto-deletes everything but the past 5 builds per env. 

Known issues:
- https://github.com/Quansight/qhub/issues/1158
- https://github.com/Quansight/qhub/issues/1021
  - related to how conda-store environments are used by CDS dashboards

**Comment by rsignell-usgs** [comment]
@iameskild , yes, I'm super confused about the new conda-store approach.    

We originally added packages to our 0.4 Qhub deployment by going to the conda-store manager https://jupyter.data.science.earth/conda-store/, choosing a namespace, and dropping an `environment.yml` file in there.    

Then we were told that if we want to have environments available for all users, we should add them in the config.yml the way we used to do and let github actions deploy them.   So I've tried that, but when I look at the conda-store manager now I see my pangeo environment with 0 bytes, and a bunch of builds not working:
![2022-04-13_08-21-37](https://user-images.githubusercontent.com/1872600/163178897-4d77f4ae-2842-4e93-9fbb-a81610f1177e.png)
![2022-04-13_08-21-11](https://user-images.githubusercontent.com/1872600/163178914-de5a1acb-161a-444e-87c9-78506d1d3b8f.png)

Questions:
* How to debug/recover from this?
* Can we still shell into the conda-store pod and delete environments?

**Comment by dharhas** [comment]
Getting back to one of my original points. 'default' and 'filesystem' are terrible names. Let's define what they are and use better names.

**Comment by viniciusdc** [comment]
@costrouc any updates on what has been decided?

**Comment by trallard** [comment]
@costrouc does this need to remain open? since everything is happening in conda-store (repo and the such) this seems stale now

**Comment by pavithraes** [comment]
Issue: In the new UI, we need to intermittently "login" to conda-store, and we need to click on the unintuitive profile icon to do so. 

Solution: Ideally, we shouldn't need to login again if we're already logged-in to Nebari. At the very least, the "login" requirement should be more obvious and intuitive.

> Dharhas said: One of the biggest overall issues with Nebari is the fact that we don't have a full single-sign on, each part requires going through the auth flow again (keycloak, argo, conda-store etc).

_Originally discussed on Slack_

**Comment by kcpevey** [comment]
This issue has been opened for a very long time and conda-store and the conda-store-ui have changed significantly. At this point, we request all UI/UX issues be opened here https://github.com/conda-incubator/conda-store-ui . 

Before closing this issue, I'll comment on the original questions:

-  When should new conda environments be created via the nebari-config.yaml and when should they be created from the /conda-store endpoint? And what difference does it make?
  - the recommendation is that all envs are built through the conda-store interface, though it is still possible that admins may want to define default envs in nebari-config.yaml. 
-  What are the steps to delete a conda environment I no longer need?
  - there is now a delete button in the ui
-  Add a feature that auto-deletes everything but the past 5 builds per env.
  - We have an open issue to improve the build deletion process and options. I've added [a note there](https://github.com/conda-incubator/conda-store/issues/591#issuecomment-1768776758)
