### ISSUE TITLE
Nebari rename steps

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari#1292]
# Step-by-step-migration plan

### Accounts and tooling

- [x] create quay.io and docker organization for nebari @aktech
- [x] Get access to PyPI nebari
- [x] create `documentation` repository and move docs to this directory
- [x] create `images` repository and move images to this directory and kickoff CI building images
    - [x] #1174

### Tasks to be done

- [x] #1445
- [x] #1446
- [ ] #1447
- [x] Create rename milestone 
  - [x] assign issues and tasks
- [x] #1395 
- [x] Open PR for CI/CD to work on both, `<release-branch>` and `main`
- [x] #1448
- [ ] #1449
- [x] #1451
- [x] #1452
- [x] #1453
- [x] #1454
- [x] Delete all stale and merged branches
- [x] #1444

### Migration day end-game

These tasks are numbered to denote order in which they should be performed:

1. Wrap up `qhub` repository
   - [x] #1455
   - [x] #1456

2. Transfer repo over to `nebari-dev`

- [ ] Transfer repository to `nebari-dev` GH organisation (should also rename to nebari)
  - [x] #1457
  - [x] #1458
  - [x] #1459
  - [ ] #1460
  - [ ] `quansight/qhub-deployment-*` do not move
- [x] #1461
- [x] #1462
- [x] #1463
- [x] #1464
- [x] #1465

After the first release:

- [x] #1466

**Comment by trallard** [comment]
> * written as `Nebari` never lowercase?
Our organisation is `nebari-dev` so I assume the correct one is `nebari` lowercase - up for discussion

> * we don't use a short name always use `nebari`
correct 

> Need to be ready to pull the trigger:
Missing:
- Need to work with design to create the branding and related assets 

> All within 1 day:
> 
> * [ ]  move to `nebari-dev` github organization move qhub repo (non-destructive)
>   
>   * [ ]  `nebrari-dev/qhub`
Should be [`nebari-dev/nebari`](https://github.com/nebari-dev/nebari)

>   * [ ]  `quansight/qhub-jupyterhub-theme` -> `nebari-dev/nebari-jupyterhub-theme`
>   * [ ]  For qhub change the cirun to have a different repo quansight/qhub -> nebari-dev/nebari

>   * [ ]  `quansight/qhub-deployment-*` do not move
Is there a reason why we are not moving? Could we do a blue-green deployment if the concern is availability related?

**Comment by iameskild** [comment]
I'll move the images to the `nebari/images` repo this week.

**Comment by magsol** [comment]
> I'll move the images to the `nebari-dev/images` repo this week.

Will be bringing this up tomorrow, but: we need to make sure the images have been decoupled before moving them over to the nebari org.

**Comment by dharhas** [comment]
I like all lower case for `nebari`

**Comment by costrouc** [comment]
@trallard after revisiting I think that all of the steps are comprehensive. Looks like many of the tasks have already been completed.
