### ISSUE TITLE
META - Nebari integrations stability

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari#1309]
## Description

Meta issue used to track integrations work or issues within Nebari

## Issues related to integrations

```[tasklist]
### Clearml
- [ ] https://github.com/nebari-dev/nebari/issues/1217
- [ ] https://github.com/nebari-dev/nebari/issues/1281
- [x] https://github.com/nebari-dev/nebari/issues/932
```

```[tasklist]
### Grafana
- [x] https://github.com/nebari-dev/nebari/issues/1481
- [x] https://github.com/nebari-dev/nebari/issues/1127
- [x] https://github.com/nebari-dev/nebari/issues/757
- [ ] https://github.com/nebari-dev/nebari/issues/1120
```

```[tasklist]
### Dask
- [x] https://github.com/nebari-dev/nebari/issues/1388
- [ ] https://github.com/nebari-dev/nebari/issues/979
- [ ] https://github.com/nebari-dev/nebari/issues/1294
```

```[tasklist]
### Conda store
- [x] https://github.com/nebari-dev/nebari/issues/1594
- [ ] https://github.com/nebari-dev/nebari/issues/1507
- [x] https://github.com/nebari-dev/nebari/issues/1412
- [x] https://github.com/nebari-dev/nebari/issues/1121
- [x] https://github.com/nebari-dev/nebari/issues/1158
```

```[tasklist]
### Other

```

**Comment by dcmcand** [comment]
Closing. All high priority issues are complete. All remaining issues will stay open, but are lower priority.
