### ISSUE TITLE
ENH - Updates to kubernetes tests triggers

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari#1618]
## TODO

- [ ] Add explicit `ci skip` in a given commit to skip the kubernetes tests
- [ ] Add workflow dispatch to trigger tests manually
- [ ] other needed improvements to triggers and optimization of our resources

**Comment by kcpevey** [comment]
Check for changes added [here](https://github.com/nebari-dev/nebari/pull/1665). I just noticed we were duplicating a hard coded nebari url so I turned it into an env var. Likely won't affect this issue, but wanted to mention it in case you notice this as well :)

**Comment by Adam-D-Lewis** [comment]
I believe this is out of date, closing.  Feel free to re-open if this issue and add more details if this issue is still relevant.
