### ISSUE TITLE
[RELEASE] `2023.1.1` release checklist

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1626]
# Release Checklist

## Release details

Scheduled release date - 2023/1/31

Release captain responsible - @iameskild 

## Starting point - a new release is out

- [x] Create _this_ issue to track and discuss the upcoming release.
- [x] Use the previous release issue for any final release-specific discussions, then close.
  - This can be a good time to debrief and discuss improvements to the release process.

## Looking forward - planning

- [x] [Create milestone for next release](https://github.com/nebari-dev/nebari/milestones) (if it doesn't already exist) and link it back here.
- [x] Triage `bugs` to determine what be should included in the release and add it to the milestone.
- [x] What new features, if any, will be included in the release and add it to the milestone.
  - This will be, in large part, determined by the roadmap.
  - Is there a focus for this release (i.e. UX/UI, stabilization, etc.)?

## Pre-release process

- [x] Decide on a date for the release.
  - What outstanding issues need to be addressed?
  - Has documentation been updated appropriately?
  - Are there any breaking changes that should be highlighted?
  - Are there any upstream releases we are waiting on?
  - [Do we need to update the `dask` versions in the `nebari-dask`?](https://github.com/conda-forge/nebari-dask-feedstock/blob/main/recipe/meta.yaml#L13-L16)
  - Will there be an accompanying blog post?
- [x] Prepare for the release.
  - [x] Announce build freeze.
  - [x] Release Candidate (RC) cycle.
    - Is this a hotfix?
      - No 
    - [x] Perform end-to-end testing. [Use the Testing Checklist template.](https://github.com/nebari-dev/nebari/issues/new?assignees=&labels=type%3A+release+%F0%9F%8F%B7&template=testing-checklist.md&title=Testing+checklist+for+<version>)
      - For minor releases, relying on the end-to-end integration tests might suffice.
    - [x] [Cut RC via GHA release workflow (w/ "This is a pre-release" checked).](https://github.com/nebari-dev/nebari/releases/new)
    - [x] End-user validation.
      - If possible, pull in volunteers to help test.
      - (Repeat steps if necessary)
  - [x] [Update `RELEASE.md` notes.](https://github.com/nebari-dev/nebari/blob/main/RELEASE.md)

## Cut the official release

_These steps must be actioned in the order they appear in this checklist._

- [x] [Tag, build and push docker images](https://github.com/nebari-dev/nebari-docker-images/releases/new)
- [x] [Update and cut release for `nebari-dask` meta package on Conda-Forge.](https://github.com/conda-forge/nebari-dask-feedstock)
- [x] [Cut PyPI release via GHA release workflow.](https://github.com/nebari-dev/nebari/releases/new)
  - Avoid appending `v` to tag.
    - Copy release notes from `RELEASE.md`.
- [x] Merge release branch into `main`
- [ ] [Merge automated release PR for `nebari` on Conda-Forge.](https://github.com/conda-forge/nebari-feedstock)

**Comment by iameskild** [comment]
https://github.com/nebari-dev/nebari/milestone/19

**Comment by iameskild** [comment]
[Testing checklist](https://github.com/nebari-dev/nebari/issues/1627)

**Comment by iameskild** [comment]
[RC1 available on PyPi](https://pypi.org/project/nebari/2023.1.1rc1/)

**Comment by iameskild** [comment]
I ran into issues with the JupyterHub docker image due to a recent change in the sqlalchemy, see this issue for details: https://github.com/nebari-dev/nebari-jupyterhub-theme/issues/14

**Comment by iameskild** [comment]
Blocked until we can sort out the dependencies needed for conda-forge release: https://github.com/conda-forge/nebari-feedstock/pull/3
