### ISSUE TITLE
META - Add playwright tests to replace (& expand) Cypress

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#1653]
### Feature description

Playwright is more user friendly than our current cypress tests. We'd like to move towards testing with playwright. The ultimate goal is to test all of our integrations through playwright on CI. 

### Value and/or benefit

Because its more user-friendly, adding more tests will require less effort and we'll be able to fill out the test suite. 

### Tasks

```[tasklist]
### Preliminary
- [ ] https://github.com/nebari-dev/nebari/pull/1665
```

```[tasklist]
### Basic tests
- [x] Login to nebari and launch a server
```

```[tasklist]
### Integration tests
- [x] Run a Jupyter notebook (high prio)
- [ ] Run a Python script via VSCode
- [ ] Run a Dask gateway job
- [ ] Run a kbatch job
- [ ] Create a new env in conda store (high prio)
- [ ] Jupyter Scheduler
```

**Comment by kcpevey** [comment]
Basic
* [ ] Login to nebari and launch a server

Integration tests
* [ ] Run a jupyter notebook
* [ ] launch a dashboard via cds dashboards
* [ ] Run a python script via VS Code
* [ ] Run a dask gateway job
* [ ] Run a kbatch job
* [ ] Create a new environment in conda-store

**Comment by trallard** [comment]
@kcpevey do we have a PR for this (even if WIP)?

**Comment by kcpevey** [comment]
This is the initial - https://github.com/nebari-dev/nebari/pull/1665. It won't close this issue so its not directly linked to this issue (only mentioned)

**Comment by kcpevey** [comment]
@aktech can you update the check boxes with the current state?

**Comment by iameskild** [comment]
I think we can consider this closed. All of the remaining items are being tracked here: https://github.com/nebari-dev/nebari/issues/1958
