### ISSUE TITLE
[META] Jupyter-Scheduler integration enhancements

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1838]
### Nebari-specific enhancements
- [ ] Create short-lived ARGO_TOKENs on a per user basis
- [ ] Use the Keycloak API to determine which `roles` the user has instead of relying on `groups`
	- Use this to grant the appropriate level of access to Argo-Workflows

### Argo-Jupyter-Scheduler enhancements
- [x] Come up with a better name for this extension plugin
- [ ] Generalize the code base so that this extension can be used without Nebari
	- [ ] Add traitlets to make it easier to mount additional volumes/secrets/configmaps (as a replacement for the Nebari Workflow Controller which we currently use to mount these resources to the workflow pod)
	- [ ] Inside the `task-runner`, run a clean up command that updates the database to reflect which workflows/cron-workflows are still active
	- [ ] Test this extension can be used with an external database
- [ ] Limit the environments that appear in the UI to only those that have `papermill` installed
- [ ] Allow modifications to `output-directory` format (for Job Definitions)
  - [ ] Rename output directory to something that's easier to find
- [ ] https://github.com/nebari-dev/argo-jupyter-scheduler/issues/2 

### Long-term enhancements
- [ ]  Make jupyter-scheduler work directly with kubernetes cron (remove reliance on argo, and more argo into a separate extension)

**Comment by Adam-D-Lewis** [comment]
Impersonation is supported with the python keycloak client so we should be able to get a short lived token fairly easily.

**Comment by ericdatakelly** [comment]
Nice to have - grab the environment name that the notebook is currently using, then make that the default selection under Environment in the Create Job page.

**Comment by krassowski** [comment]
>  Limit the environments that appear in the UI to only those that have `papermill` installed

A good start would be showing a useful error when the job fails due to lack of `papermill` - currently it is hard to debug it.

![image](https://github.com/nebari-dev/nebari/assets/5832902/a2b5d79b-63f8-4037-a0f6-2e4926241747)

**Comment by krassowski** [comment]
Cross-ref https://github.com/nebari-dev/argo-jupyter-scheduler/issues/8
