### ISSUE TITLE
AWS basic deployment

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1951]
```[tasklist]
### Tasks
- [ ] Add GHA workflow (with parameterized inputs)
- [ ] GPU
- [ ] Custom VPC
- [ ] Spot instances (preemptible)
- [ ] Upgrade from previous version
- [ ] Redeploy via GitHub-Actions
- [ ] Redeploy via GitLab-CI
```

**Comment by pavithraes** [comment]
Resolved by #1977
