### ISSUE TITLE
META - Extension System Testing CLI Commands

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1955]
```[tasklist]
### CLI Commands
- [x] cli command `init`
- [ ] https://github.com/nebari-dev/nebari/issues/1944
- [x] cli command `dev`
- [x] cli command `validate`
- [x] cli command `keycloak`
- [x] cli command `support`
- [x] cli command `upgrade`
- [ ] https://github.com/nebari-dev/nebari/issues/1978
- [x] cli setting secrets via environment variables `NEBARI_SECRET__a__b=asdf` -> `{"a": {"b": "asdf"}}` in `yaml`
```

**Comment by iameskild** [comment]
Thanks a lot for all your work on these tests @sblair-metrostar and @kenafoster! 

Marking this as complete and transferring the two lower priority issues to https://github.com/nebari-dev/nebari/issues/1958
