### ISSUE TITLE
[ENH] - Create a Nebari Makefile for Local deployment and CI

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#2489]
### Feature description

Currently, our tests GitHub Actions. Transitioning these installation workflows to a Makefile could alleviate some of the maintainers' burdens by simplifying the process of running tests locally. This move would streamline testing and potentially improve efficiency.

### Value and/or benefit

- Better docs on this approach
- More control on tracking testing versions
- More testing

```[tasklist]
### Tasks
- [ ] `make init`: Install Local copy Nebari and any dependencies
- [ ] `make deploy-local`: Deploy local version of nebari and create an example user.
- [ ] `make clean`: Delete deployment.
- [ ] `make test-unit`: Pytests
- [ ] `make test-playwright`: Playwright tests.
- [ ] `make test-integration`: run integration tests
- [ ] `make test-all`: run all tests
```

**Comment by pt247** [comment]
To ensure that the Makefile is always up-to-date, @dcmcand suggested using it in CI. Creating Makefile with steps followed in [.github/workflows/test_local_integration.yaml](https://github.com/nebari-dev/nebari/blob/develop/.github/workflows/test_local_integration.yaml) would be an excellent place to start. 
We can initially introduce the following make commands:
1. `make init`: This defaults to local deployment.
    a. If the OS is Mac, it verifies that the `docker-mac-net-connect` service is running.
    b. Install Nebari and playwright - [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L73C15-L73C44). 
    c. Initilizes Nebari like in CI for local deployment [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L94)
2. `make deploy`:
    a. Deploy Nebari [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L124).
    b. Basic kubectl checks after deployment - [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L129).
    c. Check nebari url resolves - [like](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L134).
    d. Curl jupyterhub login page - [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L138)
    e. Create example-user - [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L142).
3. `make test`:
    a. setup-node - [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L148) 
    b. `make run-cypress-tests` - [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L155).
    c. `make run-playwright-tests` [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L164).
    d. `make run-unit-tests` [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L176).
4. `make clean`:
    a. Cleanup nebari deployment - [link](https://github.com/nebari-dev/nebari/blob/363cb0d92c72e13fee84312a7ae19e1054d95326/.github/workflows/test_local_integration.yaml#L194C15-L194C40).
    b. `kind delete  clusters test-cluster`
   
In later PRs, we can extend the same for other providers like GCP, DO, and AWS. For example: 
`make init --provider=AWS`
Other commands can remain the same, except they will run against cloud instances determined by local environment variables. This should let us run cloud-based integration tests.

**Comment by viniciusdc** [comment]
good point, @pt247; I was only considering including the playwright/cypress installation and test execution commands. But its a really neat idea to also incorporate the deploy/init structures.

**Comment by pt247** [comment]
Let's use this issue as a super issue to track progress on Nebari Makefile sub-issues/tasks. 
Renaming the issue to Nebari Makefile.

**Comment by viniciusdc** [comment]
Thanks @pt247, I was about to assign you to this as well 😄

**Comment by pt247** [comment]
With the above git gist we can now spin up a local cluster for testing using the make file. 
It still uses Cloudflare for DNS-01 challange so that Letsencrypt can generate certificates that work locally. 

Main issues with this setup is that it needs Cloudflare setup for usable certificates.

There are requirements: 
1. UI: Ability to login and create enviroments and notebooks. (<-- this needs certificates)
2. Run integration tests locally. (<-- this does not need certificate)

We need to find alternatives for local testing some links worth exploring:
1. https://cert-manager.io/docs/configuration/selfsigned/
2. https://skarlso.github.io/2023/10/25/self-signed-locally-trusted-certificates-with-cert-manager/

**Comment by pt247** [comment]
Limiting the scope of this ticket: 
We should focus on local certificates while we are working on #2238. 
In this ticket, we will focus on replace CI tests in Makefile.

**Comment by pt247** [comment]
Updated [gist](https://gist.github.com/pt247/95ef1f6b88b6238be6ac57461e079024) with the latest Makefile with playwright tests.

**Comment by dcmcand** [comment]
This issue is still up for grabs. #2554 was closed as it had gotten stale, but can serve as a reference for future work
