### ISSUE TITLE
Testing checklist for 2024.7.1

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#2596]
# Testing Checklist

_Use/modify this checklist to capture the platform's core services that need to be manually tested ._

## Manual testing: core services

If the integration tests for all of the cloud providers are successful, that is a good sign!
However, the following core services still need to be manually validated (until we can automate them).

At minimum, the following services will need to be tested:

- [x] [Log into keycloak as root user](https://www.nebari.dev/docs/how-tos/configuring-keycloak/#change-keycloak-root-password)
  - [x] [Add a user](https://www.nebari.dev/docs/how-tos/configuring-keycloak/#adding-a-nebari-user)
- [x] [Log into conda-store and create](https://www.nebari.dev/docs/tutorials/creating-new-environments)
  - [x] a conda environment in a shared namespace and,
  - [x] a conda environment in your personal namespace
- [x] [Launch dask-gateway cluster, test auto-scaler and](https://www.nebari.dev/docs/tutorials/using_dask)
  - [x] [Validate that the dask-labextention is working](https://www.nebari.dev/docs/tutorials/using_dask/#step-4---understand-dasks-diagnostic-tools)
- [x] [Confirm that a notebook can be submitted via Jupyter-Scheduler](https://nebari.dev/docs/tutorials/jupyter-scheduler)
- [x] [Open VS-Code extension](https://www.nebari.dev/docs/how-tos/using-vscode)
  - [x] [Add the Python extension](https://www.nebari.dev/docs/how-tos/using-vscode#adding-extensions)
  - [x] [Create a `.py` file and run it](https://www.nebari.dev/docs/how-tos/using-vscode#running-python-code)

**Comment by viniciusdc** [comment]
uhm... got a waird behaviour going on with conda-store 
![image](https://github.com/user-attachments/assets/c81835e7-31ae-4a63-97b0-4352dd6015df)

**Comment by viniciusdc** [comment]
I think this might be related to how I deployed, will test again tomorrow morning.

**Comment by viniciusdc** [comment]
Double-check, that extensions are working, after the new release of jhub-apps make sure that the new updates made to front will work as expected.

**Comment by viniciusdc** [comment]
Due to a broken state of conda-store found while testing the 2024.7.1rc1, we decided to postpone the upgrade of conda-store from `2024.3.1` to `2024.6.1` to the next release to test and conclude the July one promptly. One extra addition to this release will be the inclusion of the latest version of Jhub-apps

**Comment by viniciusdc** [comment]
Removal of the latest version worked flawlessly within the recent RC `2024.7.1rc2`

**Comment by viniciusdc** [comment]
Will test tomorrow morning with a proper DNS for the cronjobs and dask extension

**Comment by viniciusdc** [comment]
Tested deployment on AWS, dask extension is working as expected 
![Captura de tela de 2024-08-06 16 37 39](https://github.com/user-attachments/assets/04a512b5-81f9-4944-971a-fc6275095aaf)

and the notebook scheduler 
![image](https://github.com/user-attachments/assets/540ab09f-206b-447b-b4de-fcbd3274e499)

**Comment by viniciusdc** [comment]
Found a bug with AWS, unfortunatly #2613

**Comment by kcpevey** [comment]
2024.7.1 has been released.
