### ISSUE TITLE
[EPIC] - Nebari Backup & Restore

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#2648]
This meta issue tracks the progress of implementing backup and restore functionality for our services. The original Request for Discussion (RFD) can be found [here](https://github.com/nebari-dev/governance/issues/49). The primary goal of this initiative is to provide an easily accessible solution for users to migrate cluster states during Nebari upgrades. 

The first iteration focuses on services including Keycloak, Conda-store, and NFS data.

- [ ] Discovery of viable tools and reconciliation workflows for each service
	- Research and identify effective backup and restore tools compatible with each service (Keycloak, Conda-store, and NFS).
- [ ] initial architecture development
	- Design the initial architecture for the backup and restore system. 
- [ ] [META] Implementation of backup-restore import/export services connectors

**Comment by viniciusdc** [comment]
Later, after the first iteration, the main code will merge with Nebari's to reduce the attrition of painting to sources. Also, it's expected that some schema requirements will be available to new services in the future for dynamically including them as part of the backup process. 

Though this heavily depends on merging our docker images, code back to Nebari's main repo.
