### ISSUE TITLE
[DEV] - Ensure we have adequate instance sizes in nebari

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari#37]
## Summary
Right now, all the instance sizes are too small, they need adjusting based on:

1. Small/Large/High Mem/Cheap GPU etc
2. Is our default conda store pod size reasonable
3. Are our Dask workers configured correctly for our instance sizes
4. We may be able to use the ESIP deployment as an example.

## Tasks to complete

- [ ] Determine new sizes needed
- [ ] Update the corresponding configuration/infra items
- [ ] Ensure dask workers are configured accordingly
- [ ] Increase conda store pod size

## Related to
- https://github.com/Quansight/qhub/issues/1111

**Comment by trallard** [comment]
Assign to Peyton

**Comment by peytondmurray** [comment]
Closed by https://github.com/Quansight/qhub/pull/1338.
